### ISSUE TITLE
'ErrorException' with message 'Undefined index: Range'

### ISSUE THREAD

**Issue by RckMrkr** [vimeo/vimeo.php#79] opened 2015-06-24 08:37 UTC
I get an error when trying to upload a file. The error occurs on line 406 of Vimeo.php.
After some debugging I found out that it is because there simply are no headers. The status code is 100, suggesting that the file is not completely transferred, but I am not able to find out how much was actually transferred.

There is not body either.

The quota is being checked and there is still more than enough space to transfer the video.

**Comment by Dashron** [comment] 2015-06-25 19:00
Can you try again, and post the full contents of `$progress_check` on this line: https://github.com/vimeo/vimeo.php/blob/master/src/Vimeo/Vimeo.php#L403 and the return value of this call to _request: https://github.com/vimeo/vimeo.php/blob/master/src/Vimeo/Vimeo.php#L398

**Comment by RckMrkr** [comment] 2015-06-30 10:14
var_dump of the _request:
array(3) {
  ["body"]=>
  bool(false)
  ["status"]=>
  int(200)
  ["headers"]=>
  array(10) {
    ["Server"]=>
    string(9) "Vimeo/1.0"
    ["Content-Type"]=>
    string(10) "text/plain"
    ["Access-Control-Allow-Origin"]=>
    string(1) "*"
    ["Access-Control-Expose-Headers"]=>
    string(5) "Range"
    ["Access-Control-Allow-Headers"]=>
    string(46) "Content-Type, Content-Range,  X-Requested-With"
    ["X-Requested-With"]=>
    string(14) "XMLHttpRequest"
    ["Access-Control-Allow-Methods"]=>
    string(23) "POST, PUT, GET, OPTIONS"
    ["Content-Length"]=>
    string(1) "0"
    ["Connection"]=>
    string(5) "close"
    ["Date"]=>
    string(19) "Tue, 30 Jun 2015 10"
  }
}

var_dump of $progress_check:
array(3) {
  ["body"]=>
  bool(false)
  ["status"]=>
  int(100)
  ["headers"]=>
  array(0) {
  }
}

In order to get this info, I had to do it twice because it worked the first time.
Second time it was like this.
The response from _request the first time was identical to the one I got the second time.

**Comment by Dashron** [comment] 2015-06-30 12:26
Can you post the parameters you send to the progress check? My guess is some part of it is **very** long.

You can probably fix this by adding the `Expect: ` header you see here: https://github.com/vimeo/vimeo.php/blob/master/src/Vimeo/Vimeo.php#L378 on to the array of headers here: https://github.com/vimeo/vimeo.php/blob/master/src/Vimeo/Vimeo.php#L384


The final list should look like this:

`CURLOPT_HTTPHEADER => array('Expect: ', 'Content-Length: 0', 'Content-Range: bytes */*')`


The issue is that when curl makes HTTP requests over a certain size (I believe it's 1mb), it won't actually make the request. It makes a trimmed down request with an expect header asking if the server is ok with curl making the larger request. If the server is ok with curl making this larger request, it will return a `100 continue` status code.

Unfortunately there is no clear flag to disable this setting. You have to just pass in your own empty expect header so curl won't override it.

**Comment by RckMrkr** [comment] 2015-07-01 07:03
I just did a var_dump($progress_check, $url, $curl_opts_check_progress), and got the following:
array(3) {
  ["body"]=>
  bool(false)
  ["status"]=>
  int(100)
  ["headers"]=>
  array(0) {
  }
}
string(365) "https://1511655186.cloud.vimeo.com/upload?ticket_id=d7e8804cebe2a533f2bc71a3cba51af1&video_file_id=386931084&signature=b086b0fb06e0bec78d696ad34235d30f&v6=1&full_hd=0&redirect_url=https%3A%2F%2Fvimeo.com%2Fupload%2Fapi%3Fvideo_file_id%3D386931084%26app_id%3D48215%26ticket_id%3Dd7e8804cebe2a533f2bc71a3cba51af1%26signature%3D6f0aa1e577edb42c22cff11c7ff17b03c2067f7e"
array(2) {
  [54]=>
  bool(true)
  [10023]=>
  array(2) {
    [0]=>
    string(17) "Content-Length: 0"
    [1]=>
    string(24) "Content-Range: bytes */*"
  }
}

It is a long url, but not anywhere near 1MB.

If i insert the "Expect"-header i get a curl error:
Unable to complete request.[read function returned funny value]

**Comment by inctor** [comment] 2015-09-11 07:01
Hey @Dashron ,

I work together with Rick, he's no longer employed at our company, and i've taken over this issue/case.

Is there any news on this?
We're still experiencing this issue and our queue only retries an upload 3 times before moving it to failed.

And i still get 5-6 failed uploads everyday..

These are dumps from our log-files that show the headers returned from the upload function.
```
[2015-09-10 21:00:00] production.INFO: starting upload job {"data":{"user_id":"271","model_id":1462,"video_path":"/*/app/storage/upload/4048.mp4","company_id":"2"}} []
[2015-09-10 21:00:00] production.INFO: Now we are about to upload {"jobid":40599,"path":"/*/app/storage/upload/4048.mp4"} []
[2015-09-10 21:00:02] production.INFO: vimeo headers [{"body":false,"status":100,"headers":[]}] []
[2015-09-10 21:00:02] production.INFO: Issue with Vimeo connection [] []

[2015-09-10 21:00:08] production.INFO: starting upload job {"data":{"user_id":"271","model_id":1462,"video_path":"/*/app/storage/upload/4048.mp4","company_id":"2"}} []
[2015-09-10 21:00:08] production.INFO: Now we are about to upload {"jobid":40599,"path":"/*/app/storage/upload/4048.mp4"} []
[2015-09-10 21:00:10] production.INFO: vimeo headers [{"body":false,"status":100,"headers":[]}] []
[2015-09-10 21:00:11] production.INFO: Issue with Vimeo connection [] []

[2015-09-10 21:00:16] production.INFO: starting upload job {"data":{"user_id":"271","model_id":1462,"video_path":"/*/app/storage/upload/4048.mp4","company_id":"2"}} []
[2015-09-10 21:00:16] production.INFO: Now we are about to upload {"jobid":40599,"path":"/*/app/storage/upload/4048.mp4"} []
[2015-09-10 21:00:19] production.INFO: vimeo headers [{"body":false,"status":100,"headers":[]}] []
[2015-09-10 21:00:19] production.INFO: Issue with Vimeo connection [] []
```

And another one from shortly after from retrying to upload it:
```
[2015-09-10 21:01:15] production.INFO: starting upload job {"data":{"user_id":"271","model_id":"1462","video_path":"/*/app/storage/upload/4049.mp4","company_id":"2"}} []
[2015-09-10 21:01:15] production.INFO: Now we are about to upload {"jobid":40600,"path":"/*/app/storage/upload/4049.mp4"} []
[2015-09-10 21:01:17] production.INFO: vimeo headers [{"body":false,"status":100,"headers":[]}] []
[2015-09-10 21:01:17] production.INFO: Issue with Vimeo connection [] []
[2015-09-10 21:01:22] production.INFO: starting upload job {"data":{"user_id":"271","model_id":"1462","video_path":"/*/app/storage/upload/4049.mp4","company_id":"2"}} []
[2015-09-10 21:01:22] production.INFO: Now we are about to upload {"jobid":40600,"path":"/*/app/storage/upload/4049.mp4"} []
[2015-09-10 21:01:25] production.INFO: vimeo headers [{"body":false,"status":308,"headers":{"":"","HTTP/1.1 308 Resume Incomplete":"","Server":"Vimeo/1.0","Content-Type":"text/plain","Access-Control-Allow-Origin":"*","Timing-Allow-Origin":"*","Access-Control-Expose-Headers":"Range","Access-Control-Allow-Headers":"Content-Type, Content-Range,  X-Requested-With","X-Requested-With":"XMLHttpRequest","Access-Control-Allow-Methods":"POST, PUT, GET, OPTIONS","Content-Length":"0","Connection":"close","Range":"bytes=0-23933900","Date":"Thu, 10 Sep 2015 21","X-Backend-Server":"kopiluwak"}}] []
```

We really want a solution to this issue, that doesn't involve changing the core-code of your package.

**Comment by Dashron** [comment] 2015-09-11 16:46
The space I included in the expect header may have caused an issue. In some of our own code for third party libraries we have the following code.

`CURLOPT_HTTPHEADER => array('Expect:')`. It should avoid any 100 errors. Is the error still happening on progress checks?

**Comment by inctor** [comment] 2015-09-14 07:27
Hey @Dashron,
Thanks for getting back to me.

I checked further in to the issue, and tried with both space and no-space, and the issue persisted.
However, not all the times, only at random times.

The possible fault was likely on our end, rather than on your end, as it seems there is some issues with HHVM and the "Expect" header, and the 100-Continue header as well.
It's not being handled properly and throws this error.

After switching our queue handler back to using PHP5-FPM, i haven't received any failed jobs about failing uploads..

It appears that the cURL implementation in HHVM is not 100% solid, and doesn't support that header properly.

I apologize for my colleague and me not mentioning the fact we're using HHVM earlier, but it just didn't seem like that was the issue when we were looking into it and trying different solutions.

I see now, that the issue is on HHVM, and not your Package, so we'll hope that the HHVM development team will manage to do a proper implementation of the header-handling to cURL, so we can use it again for our queue manager :)

Thanks a lot for your assistance in this though!
Really appreciated :)

**Comment by Dashron** [comment] 2015-09-14 16:25
Oh interesting. So my guess is that HHVM might have a different way of removing default headers. The system we have above is a hack to ensure that curl doesn't add the expect header for any requests.

This might be worth a bug report on the HHVM project.

**Closed by Dashron** 2015-09-14 16:25 UTC
