### ISSUE TITLE
SSL certificate problem: certificate has expired

### ISSUE THREAD

**Issue by mathieuCatapulpe** [vimeo/vimeo.php#336] opened 2024-03-25 11:08 UTC
On an old website I inherited from my predecessor I get this error :

`Vimeo\Exceptions\VimeoRequestException : Unable to complete request. [SSL certificate problem: certificate has expired] in line 509 vimeo/vimeo-api/src/Vimeo/Vimeo.php`

Most problems I saw here concerning SSL are about Local Issuer Certificate issues, I tried some of their solutions but it didn't solve the issue.

Any ideas where it might be coming from ? It's a pretty old version of Vimeo php, but the website is running a drupal 7, so updating php version for instance might break stuff

**Comment by mpossani** [comment] 2024-03-25 11:25
I started getting the same error last week in one of our old development environments, specifically when sending a PATCH request thru Vimeo API. We don't use any framework in this environment, but it's an old version of php (5.4) and apache. We have a similar production environment working with no problem, and our brand new environments with updated php and nginx working well too. Anyone else having the same SSL certficate problem?

**Comment by Rultig** [comment] 2024-03-25 12:12
Had the exact same problem appear a couple of days ago on the production server. Seems to be working in dev environment though. 

Version 2.x on Laravel 5.6.

**Comment by aaronm67** [comment] 2024-03-25 18:54
Cert pinning was removed from this library around 3 years ago - you either need to update to the latest version of this library, or you can follow instructions in this thread to use a standard cert: https://github.com/vimeo/vimeo.php/issues/329

**Comment by mpossani** [comment] 2024-03-25 23:13
> Cert pinning was removed from this library around 3 years ago - you either need to update to the latest version of this library, or you can follow instructions in this thread to use a standard cert: #329

It didn't work for me. Same error.

**Comment by corentindechomet** [comment] 2024-03-26 07:31
> Cert pinning was removed from this library around 3 years ago - you either need to update to the latest version of this library, or you can follow instructions in this thread to use a standard cert: #329

I can confirm that the problem is different. Even after updating the library, we still get the same error.
The issue mentionned helps users to get rid of "SSL certificate problem: **unable to get local issuer certificate**" error.
Here we have the following error: "SSL certificate problem: **certificate has expired**"
We inspected "api.vimeo.com" domain, and we saw that the certificate was updated last friday (23 march). Maybe there's a connection?

**Comment by Rultig** [comment] 2024-03-26 07:40
> > Cert pinning was removed from this library around 3 years ago - you either need to update to the latest version of this library, or you can follow instructions in this thread to use a standard cert: #329
> 
> I can confirm that the problem is different. Even after updating the library, we still get the same error. The issue mentionned helps users to get rid of "SSL certificate problem: **unable to get local issuer certificate**" error. Here we have the following error: "SSL certificate problem: **certificate has expired**" We inspected "api.vimeo.com" domain, and we saw that the certificate was updated last friday (23 march). Maybe there's a connection?

That seems like the most probable cause since that was the exact day the problems started for me.

**Comment by adrianpaiva1** [comment] 2024-04-30 17:43
so how do we fix this?

**Comment by aaronm67** [comment] 2024-05-01 19:06
> so how do we fix this?

Update your system SSL Certificate, or manually install the certificates at https://letsencrypt.org/certificates

Going to close this issue, as this isn't a library issue. For further support, please reach out to https://vimeo.com/help/contact.

**Closed by aaronm67** 2024-05-01 19:06 UTC
