### ISSUE TITLE
Whoops! We are having some technical difficulties, please try again in a minute.

### ISSUE THREAD

**Issue by mtarlan** [vimeo/vimeo.php#173] opened 2018-06-22 08:13 UTC
how to fix this error. already 2 days the same error

**Comment by tommypenner** [comment] 2018-06-22 14:23
Please provide details - what specific requests are you making to the API?

**Comment by jimyaghi** [comment] 2018-06-24 11:47
For me, i get it with this request:

```
$lib->request("/me/videos", [
			"upload" => [
				"approach" => "tus",
				"size" => $req->size
			]
		], "POST");
```
Of course, i have tried this in Postman and it yields the same outcome. When setting header to use version 3.3 of the API the same request runs but i am not sure if that is a TUS resumable URL it returns.

~J

**Comment by jimyaghi** [comment] 2018-06-24 14:19
Ok i have figured out why this happens. Apparently if you start a TUS upload but do not actually complete it, you have to wait until the rate limit reset time before initiating a second TUS upload. This limitation is unfortunate in my case because i expect multiple simultaneous users to be making uploads into the same account. I wonder if there is a way to get around the limitation? Also, i have not yet tested if completing the upload automatically resets the rate limit (not that this necessarily makes a difference in my use case)

**Comment by TaktakTaktouk** [comment] 2018-06-24 22:13
I got the same issue only when I try to upload video to Business account. But this work fine for Basic account. Here is my code
`$videoData = $lib->request ( '/me/videos', array (
					'type' => 'pull',
					'link' => "https://transferring-videos.com/web/temp_videos/OjpdX.mp4"
			), 'POST' );`

**Comment by sw1tchmx** [comment] 2018-06-25 07:19
same here

**Comment by erunion** [comment] 2018-06-26 13:40
@mtarlan @jimyaghi @TaktakTaktouk @sw1tchmx Sorry for the delay! We've just pushed out a fix for this, can you see if you're still receiving the error?

**Comment by erunion** [comment] 2018-06-26 17:06
Confirmed fixed in https://github.com/vimeo/vimeo.php/issues/174#issuecomment-400390955

**Closed by erunion** 2018-06-26 17:06 UTC

**Comment by TaktakTaktouk** [comment] 2018-06-26 17:09
Just one question, why I got this error only with business account while it works fine with a basic account?

**Comment by erunion** [comment] 2018-06-26 17:36
@TaktakTaktouk We have some different upload logic in our backend depending on the account type of who is uploading.

**Comment by TaktakTaktouk** [comment] 2018-06-26 17:41
@erunion And there is no rate limit if the user tries to upload multiple videos to his account at the same time? do I risk a blocking by the Vimeo API in this case

**Comment by erunion** [comment] 2018-06-26 17:53
There can be, but only in very extreme situations. Keep an eye on your rate limit headers to see what your limits are. https://developer.vimeo.com/guidelines/rate-limiting

**Comment by jimyaghi** [comment] 2018-06-26 21:52
i confirm it's working also! Thank you so much!
